config/routes.rb
Snorby::Application.routes.draw do

  resources :lookups

  # This feature is not ready yet
  # resources :notifications

  resources :jobs do
    member do
      get :last_error
      get :handler
    end
  end

  resources :classifications

  devise_for :users, :path_names => { :sign_in => 'login', 
    :sign_out => 'logout', 
    :sign_up => 'register' }, :controllers => { 
      :registrations => "registrations",
      :sessions => "sessions", 
      :passwords => 'passwords'
    } do
    get "/login" => "devise/sessions#new"
    get '/logout', :to => "devise/sessions#destroy"
    get '/reset/password', :to => "devise/passwords#edit"
  end

  root :to => "page#dashboard"

  resources :sensors do


    collection do
      get :agent_list
    end
  end

  resources :settings do
    collection do
      get :restart_worker
      get :start_sensor_cache
      get :start_daily_cache
      get :start_geoip_update
      get :start_worker
    end
  end

  resources :signatures do

    collection do
      get :search
    end
    
  end

  resources :severities do
  end


  match '/dashboard', :controller => 'Page', :action => 'dashboard'
  match '/search', :controller => 'Page', :action => 'search'
  match '/results', :controller => 'Page', :action => 'results'
  match '/force/cache', :controller => "Page", :action => 'force_cache'
  match '/cache/status', :controller => "Page", :action => 'cache_status'
  match '/search/json', :controller => "Page", :action => 'search_json'

  resources :saved_searches, :path => "/saved/searches" do
    
    collection do
      post :title
      post :update
    end

    member do
      get :view
      post :update
    end
  end

  match ':controller(/:action(/:sid/:cid))', :controller => 'Events'

  resources :asset_names do
    member do
      delete :remove
    end

    collection do
      post :add
      get :lookup
      post :bulk_upload
      get 'get_bulk_upload', action: :get_bulk_upload, as: 'get_bulk_upload'
    end
  end

  resources :events do
    
    resources :notes do
      
    end
    
    collection do
      get :sessions
      get :view
      get :create_mass_action
      post :mass_action
      get :create_email
      post :email
      get :hotkey
      post :export
      get :lookup
      get :rule
      get :packet_capture
      get :history
      post :classify
      post :classify_sessions
      post :mass_update
      get :queue
      post :favorite
      get :last
      get :since
      get :activity
    end
    
  end
  
  resources :notes

  resources :users do
    collection do
      post :toggle_settings
      post :remove
      post :add
    end
  end

  resources :page do
    collection do
      get :search
      get :results
    end
  end

end

app/models/lookup.rb
class Lookup
  include DataMapper::Resource

  property :id, Serial

  property :title, String

  property :value, Text


  def build(args={})
    args.fetch(:ip, '')
    args.fetch(:port, '')
    value.sub(/\$\{ip\}/, "#{args[:ip]}").sub(/\$\{port\}/, "#{args[:port]}")
  end

end

app/controllers/lookups_controller.rb
class LookupsController < ApplicationController

  before_filter :require_administrative_privileges

  # GET /lookups
  # GET /lookups.xml
  def index
    @lookups = Lookup.all.page(params[:page].to_i, :per_page => @current_user.per_page_count, :order => [:id.asc])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lookups }
    end
  end

  # GET /lookups/1
  # GET /lookups/1.xml
  def show
    @lookup = Lookup.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @lookup }
    end
  end

  # GET /lookups/new
  # GET /lookups/new.xml
  def new
    @lookup = Lookup.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @lookup }
    end
  end

  # GET /lookups/1/edit
  def edit
    @lookup = Lookup.get(params[:id])
  end

  # POST /lookups
  # POST /lookups.xml
  def create
    @lookup = Lookup.new(params[:lookup])

    respond_to do |format|
      if @lookup.save
        format.html { redirect_to(lookups_url, :notice => 'Lookup source successfully created.') }
        format.xml  { render :xml => @lookup, :status => :created, :location => @lookup }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @lookup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lookups/1
  # PUT /lookups/1.xml
  def update
    @lookup = Lookup.get(params[:id])

    respond_to do |format|
      if @lookup.update(params[:lookup])
        format.html { redirect_to(lookups_url, :notice => 'Lookup source successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @lookup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lookups/1
  # DELETE /lookups/1.xml
  def destroy
    @lookup = Lookup.get(params[:id])
    @lookup.destroy

    respond_to do |format|
      format.html { redirect_to(lookups_url, :notice => 'Lookup source removed successfully.') }
      format.xml  { head :ok }
    end
  end
end

app/helpers/lookups_helper.rb
module LookupsHelper
end

app/views/lookups/_form.html.erb
<div class="note lookups" style='margin:10px;'>
  Lookup sources are available within the event show view via the source &
  destination address menus. A following are allowed URL variables: ${ip} and ${port}. 

  <strong>Example: http://www.example.com/lookup?address=${ip}</strong>
</div>

<div id='lookup-form' class='grid_12 boxit page'>
	<%= form_for @lookup, :html => { :class => 'validate' } do |f| %>
	  
		<%= error_messages_for(@lookup) %>
	
		<p class='form-order'>
			<%= f.label 'Lookup Title' %><br />
	  	<%= f.text_field :title, :class => 'required large', :placeholder => 'Example.com Address Lookup', :autocomplete => :off %>
		</p>
		
		<p class='form-order'>
			<%= f.label 'Lookup Source URL' %><br />
	  	<%= f.text_field :value, :class => 'required large', :placeholder => 'Source URL', :autocomplete => :off %>
		</p>

		<%= form_actions do %>

			<%= button "Save lookup Source", :class => 'success' %>

			<%= button "Cancel", :class => 'warning cancel' %>

		<% end %>
	
	<% end %>
	
</div>

app/views/lookups/_lookup.html.erb
<tr>
	<td class='first'><%= lookup.title %></td>
	<td><%= lookup.value %></td>	
  <td><%= link_to "Edit", edit_lookup_path(lookup) %></td>
  <td class='last'><%= link_to image_tag("icons/destroy.png", :size => '16x16', :class => 'trash'), lookup_path(lookup), :method => :delete, :confirm => 'Are you sure you want to remove this lookup?' %></td>
</tr>

app/views/lookups/edit.html.erb
<%= title "Edit Lookup Source" do -%>

	<%= render :partial => 'settings/menu' %>
	
<%- end -%>

<%= render 'form' %>

app/views/lookups/index.html.erb
<%= title "Lookup Sources" do -%>

	<%= menu_item "Add Lookup Source", new_lookup_path, 'icons/add.png' %>
	<%= render :partial => 'settings/menu' %>
	
<%- end -%>

<div id="lookups" class='grid_12 page boxit'>
	
	<table class='default' border="0" cellspacing="0" cellpadding="0">
		<tr>		
			<th>Menu Title</th>
			<th>URL</th>
			<th>Edit</th>
			<th>Destroy</th>
		</tr>
		<tbody class='lookups'>
			<%= render @lookups %>
		</tbody>
	</table>

	<%= pager(@lookups, Snorby::CONFIG[:baseuri] + '/lookups') %>
	
</div>

app/views/lookups/new.html.erb
<%= title "New Lookup Source" do -%>

	<%= render :partial => 'settings/menu' %>
	
<%- end -%>

<%= render 'form' %>

app/views/lookups/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_lookup_path(@lookup) %> |
<%= link_to 'Back', lookups_path %>