config/routes.rb
Snorby::Application.routes.draw do

  resources :lookups

  # This feature is not ready yet
  # resources :notifications

  resources :jobs do
    member do
      get :last_error
      get :handler
    end
  end

  resources :classifications

  devise_for :users, :path_names => { :sign_in => 'login', 
    :sign_out => 'logout', 
    :sign_up => 'register' }, :controllers => { 
      :registrations => "registrations",
      :sessions => "sessions", 
      :passwords => 'passwords'
    } do
    get "/login" => "devise/sessions#new"
    get '/logout', :to => "devise/sessions#destroy"
    get '/reset/password', :to => "devise/passwords#edit"
  end

  root :to => "page#dashboard"

  resources :sensors do


    collection do
      get :agent_list
    end
  end

  resources :settings do
    collection do
      get :restart_worker
      get :start_sensor_cache
      get :start_daily_cache
      get :start_geoip_update
      get :start_worker
    end
  end

  resources :signatures do

    collection do
      get :search
    end
    
  end

  resources :severities do
  end


  match '/dashboard', :controller => 'Page', :action => 'dashboard'
  match '/search', :controller => 'Page', :action => 'search'
  match '/results', :controller => 'Page', :action => 'results'
  match '/force/cache', :controller => "Page", :action => 'force_cache'
  match '/cache/status', :controller => "Page", :action => 'cache_status'
  match '/search/json', :controller => "Page", :action => 'search_json'

  resources :saved_searches, :path => "/saved/searches" do
    
    collection do
      post :title
      post :update
    end

    member do
      get :view
      post :update
    end
  end

  match ':controller(/:action(/:sid/:cid))', :controller => 'Events'

  resources :asset_names do
    member do
      delete :remove
    end

    collection do
      post :add
      get :lookup
      post :bulk_upload
      get 'get_bulk_upload', action: :get_bulk_upload, as: 'get_bulk_upload'
    end
  end

  resources :events do
    
    resources :notes do
      
    end
    
    collection do
      get :sessions
      get :view
      get :create_mass_action
      post :mass_action
      get :create_email
      post :email
      get :hotkey
      post :export
      get :lookup
      get :rule
      get :packet_capture
      get :history
      post :classify
      post :classify_sessions
      post :mass_update
      get :queue
      post :favorite
      get :last
      get :since
      get :activity
    end
    
  end
  
  resources :notes

  resources :users do
    collection do
      post :toggle_settings
      post :remove
      post :add
    end
  end

  resources :page do
    collection do
      get :search
      get :results
    end
  end

end

app/models/classification.rb
require 'snorby/model/counter'

class Classification

  include DataMapper::Resource
  include Snorby::Model::Counter

  property :id, Serial, :index => true

  property :name, String

  property :description, Text

  property :hotkey, Integer, :index => true

  property :locked, Boolean, :default => false, :index => true

  property :events_count, Integer, :index => true, :default => 0

  has n, :events, :constraint => :destroy

  validates_uniqueness_of :hotkey
  
  validates_presence_of :name
  
  validates_presence_of :description

  def shortcut
    "f#{hotkey}"
  end

  #
  #  
  # 
  def event_percentage
    begin
      ((self.events_count.to_f / Event.count.to_f) * 100).round(2)
    rescue FloatDomainError
      0
    end
  end
  
  
  def self.to_graph
    graph = []
    all.each do |classification|
      graph << {
        :name => classification.name,
        :data => classification.events_count
      }
    end
    graph
  end
  
  def self.to_pie
    graph = []
    all.each do |classification|
      graph << [classification.name, classification.events_count] unless classification.events_count.zero?
    end
    graph
  end

end

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController

  before_filter :require_administrative_privileges

  def index
    @classifications = Classification.all.page(params[:page].to_i, :per_page => @current_user.per_page_count, :order => [:id.asc])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @classifications }
    end
  end

  def show
    @classification = Classification.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @classification }
    end
  end

  def new
    @classification = Classification.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @classification }
    end
  end

  def edit
    @classification = Classification.get(params[:id])
  end

  def create
    @classification = Classification.new(params[:classification])

    respond_to do |format|
      if @classification.save
        format.html { redirect_to(classifications_url, :notice => 'Classification was successfully created.') }
        format.xml  { render :xml => @classification, :status => :created, :location => @classification }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @classification.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @classification = Classification.get(params[:id])

    respond_to do |format|
      if @classification.update(params[:classification])
        format.html { redirect_to(classifications_url, :notice => 'Classification was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @classification.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @classification = Classification.get(params[:id])
    @classification.destroy!

    respond_to do |format|
      format.html { redirect_to(classifications_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/classifications_helper.rb
module ClassificationsHelper
end

app/views/classifications/_classification.html.erb
<tr>
	<td class='first'><%= classification.id %></td>
	<td><%= classification.name %></td>
	<td><%= number_with_delimiter classification.events_count %></td>
	
	<td class='chart'><%= css_chart(classification.event_percentage) %></td>
	
	<% if classification.locked %>
		<td><%= image_tag('icons/lock.png', :size => '16x16') %></td>
		<td class='last'><%= image_tag('icons/lock.png', :size => '16x16') %></td>
	<% else %>
		<td><%= link_to "Edit", edit_classification_path(classification) %></td>
		<td class='last'><%= link_to image_tag("icons/destroy.png", :size => '16x16', :class => 'trash'), classification_path(classification), :method => :delete, :confirm => 'Are you sure you want to remove this classification?' %></td>
	<% end %>
</tr>

app/views/classifications/_form.html.erb
<div id='classification-form' class='grid_12 boxit page'>
	<%= form_for @classification, :html => { :class => 'validate' } do |f| %>
	  
		<%= error_messages_for(@classification) %>
	
		<p>
			<%= f.label 'Classification Name' %><br />
	  	<%= f.text_field :name, :class => 'required', :placeholder => 'Example: Web Attacks', :autocomplete => :off %>
		</p>
		
		<p>
			<%= f.label 'Classification Description' %><br />
	  	<%= f.text_area :description, :class => 'required', :placeholder => 'Description', :autocomplete => :off %>
		</p>
	
		<%= form_actions do %>

			<%= button "Save Classification", :class => 'success' %>

			<%= button "Cancel", :class => 'warning cancel' %>

		<% end %>
	
	<% end %>
	
</div>

app/views/classifications/edit.html.erb
<%= title "Edit Classification" do -%>

	<%= render :partial => 'settings/menu' %>
	
<%- end -%>


<%= render 'form' %>

app/views/classifications/index.html.erb
<%= title "Classification Settings" do -%>

	<%= menu_item "Add Classification", new_classification_path, 'icons/add.png' %>
	<%= render :partial => 'settings/menu' %>
	
<%- end -%>

<div id="classifications" class='grid_12 page boxit'>
	
	<table class='default' border="0" cellspacing="0" cellpadding="0">
		<tr>		
			<th>ID</th>
			<th>Name</th>
			<th>Event Count</th>
			<th>Event %</th>
			<th>Edit</th>
			<th>Destroy</th>
		</tr>
		<tbody class='classifications'>
			<%= render @classifications %>
		</tbody>
	</table>

	<%= pager(@classifications, Snorby::CONFIG[:baseuri] + '/classifications') %>
	
</div>

app/views/classifications/new.html.erb
<%= title "New Classification" do -%>

	<%= render :partial => 'settings/menu' %>
	
<%- end -%>


<%= render 'form' %>

app/views/classifications/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_classification_path(@classification) %> |
<%= link_to 'Back', classifications_path %>