config/routes.rb
Snorby::Application.routes.draw do

  resources :lookups

  # This feature is not ready yet
  # resources :notifications

  resources :jobs do
    member do
      get :last_error
      get :handler
    end
  end

  resources :classifications

  devise_for :users, :path_names => { :sign_in => 'login', 
    :sign_out => 'logout', 
    :sign_up => 'register' }, :controllers => { 
      :registrations => "registrations",
      :sessions => "sessions", 
      :passwords => 'passwords'
    } do
    get "/login" => "devise/sessions#new"
    get '/logout', :to => "devise/sessions#destroy"
    get '/reset/password', :to => "devise/passwords#edit"
  end

  root :to => "page#dashboard"

  resources :sensors do


    collection do
      get :agent_list
    end
  end

  resources :settings do
    collection do
      get :restart_worker
      get :start_sensor_cache
      get :start_daily_cache
      get :start_geoip_update
      get :start_worker
    end
  end

  resources :signatures do

    collection do
      get :search
    end
    
  end

  resources :severities do
  end


  match '/dashboard', :controller => 'Page', :action => 'dashboard'
  match '/search', :controller => 'Page', :action => 'search'
  match '/results', :controller => 'Page', :action => 'results'
  match '/force/cache', :controller => "Page", :action => 'force_cache'
  match '/cache/status', :controller => "Page", :action => 'cache_status'
  match '/search/json', :controller => "Page", :action => 'search_json'

  resources :saved_searches, :path => "/saved/searches" do
    
    collection do
      post :title
      post :update
    end

    member do
      get :view
      post :update
    end
  end

  match ':controller(/:action(/:sid/:cid))', :controller => 'Events'

  resources :asset_names do
    member do
      delete :remove
    end

    collection do
      post :add
      get :lookup
      post :bulk_upload
      get 'get_bulk_upload', action: :get_bulk_upload, as: 'get_bulk_upload'
    end
  end

  resources :events do
    
    resources :notes do
      
    end
    
    collection do
      get :sessions
      get :view
      get :create_mass_action
      post :mass_action
      get :create_email
      post :email
      get :hotkey
      post :export
      get :lookup
      get :rule
      get :packet_capture
      get :history
      post :classify
      post :classify_sessions
      post :mass_update
      get :queue
      post :favorite
      get :last
      get :since
      get :activity
    end
    
  end
  
  resources :notes

  resources :users do
    collection do
      post :toggle_settings
      post :remove
      post :add
    end
  end

  resources :page do
    collection do
      get :search
      get :results
    end
  end

end

app/models/severity.rb
require 'snorby/model'

class Severity
  
  include Snorby::Model
  include DataMapper::Validate
  include DataMapper::Resource

  has n, :signatures, :child_key => :sig_priority, :parent_key => :sig_id

  property :id, Serial, :index => true, :key => true, :min => 0
  
  property :sig_id, Integer, :index => true, :min => 0
  
  property :events_count, Integer, :index => true, :default => 0, :min => 0
  
  # Set the name of the severity
  property :name, String

  # Set the severity text color
  property :text_color, String, :default => '#ffffff', :index => true
  
  # Set the severity background color
  property :bg_color, String, :default => '#dddddd', :index => true

  validates_presence_of :sig_id, :name, :text_color
  validates_uniqueness_of :sig_id
  validates_format_of :text_color, :with => /^#?([a-f]|[A-F]|[0-9]){3}(([a-f]|[A-F]|[0-9]){3})?$/, :message => "is invalid"
  validates_format_of :bg_color, :with => /^#?([a-f]|[A-F]|[0-9]){3}(([a-f]|[A-F]|[0-9]){3})?$/, :message => "is invalid"

  def locked?
    return true if [1,2,3].include?(id)
    false
  end

end

app/controllers/severities_controller.rb
class SeveritiesController < ApplicationController

  before_filter :require_administrative_privileges

  def index
    @severities = Severity.all.page(params[:page].to_i, :per_page => @current_user.per_page_count, :order => [:id.asc])
  end

  def new
    @severity = Severity.new
  end

  def create
    @severity = Severity.create(params[:severity])
    if @severity.save
      redirect_to severities_path, :notice => 'Severity Created Successfully.'
    else
      render :action => 'new', :notice => 'Error: Unable To Create Record.'
    end
  end

  def update
    @severity = Severity.get(params[:id])
    if @severity.update(params[:severity])
      redirect_to severities_path, :notice => 'Severity Updated Successfully.'
    else
      render :action => 'edit', :notice => 'Error: Unable To Save Record.'
    end
  end

  def edit
    @severity = Severity.get(params[:id])
  end

  def destroy
    @severity = Severity.get(params[:id])
    @severity.destroy
    redirect_to severities_path, :notice => 'Severity Removed Successfully.'
  end

end

app/helpers/severities_helper.rb
module SeveritiesHelper
end

app/views/severities/_form.html.erb
<% content_for :footer do %>
	<script type="text/javascript">
		$('#severity-color-bg div').css('backgroundColor', $('input#severity_bg_color').attr('value'));
		$('#severity-color-text div').css('backgroundColor', $('input#severity_text_color').attr('value'));
	</script>
<% end %>

<div id='severity-form' class='grid_12 boxit page'>
	<%= form_for @severity, :html => { :class => 'validate' } do |f| %>
	  
		<%= error_messages_for(@severity) %>
	
		<p>
			<%= f.label 'Severity Name' %><br />
	  	<%= f.text_field :name, :class => 'required', :placeholder => 'Name', :autocomplete => :off %>
		</p>
		
		<p>
			<%= f.label 'Severity Priority' %> <i>(The priority of the ids event you want to represent)</i><br />
	  	<%= f.text_field :sig_id, :class => 'required number', :placeholder => 'Priority', :autocomplete => :off %>
		</p>
		
		<p>
			<%= f.label 'Example' %>:
			<span class="severity" style='background-color: <%= @severity.bg_color %>;color: <%= @severity.text_color %>;'>Example</span><br />
		</p>
		
		<br />
		
		<p>
			<%= f.label 'Severity Background' %><br />
	  	<%= f.text_field :bg_color, :class => 'required hex-color', :id => 'severity-color-bg', :placeholder => 'Background Color', :autocomplete => :off %>
		</p>
		
		<p>
			<%= f.label 'Severity Text' %><br />
	  	<%= f.text_field :text_color, :class => 'required hex-color', :id => 'severity-color-text', :placeholder => 'Text Color', :autocomplete => :off %>
		</p>
	
		<%= form_actions do %>

			<%= button "Save Severity", :class => 'success' %>

			<%= button "Cancel", :class => 'warning cancel' %>

		<% end %>
	
	<% end %>
	
</div>

app/views/severities/_severities.html.erb
<div id="severities" class='grid_12 page boxit'>

	<table class='default' border="0" cellspacing="0" cellpadding="0">
		
		<tr>		
			<th>ID</th>
			<th>Name</th>
			<th>Background</th>
			<th>Text</th>
			<th>Signature Count</th>
			<th>Event Count</th>
			<th>Example</th>
			<th>Edit</th>
			<th>Destroy</th>
		</tr>
		
		<tbody class='sensors content'>
			<%= render @severities %>
		</tbody>
		
	</table>


	<%= pager(@severities, Snorby::CONFIG[:baseuri] + '/severities') %>
	
</div>

app/views/severities/_severity.html.erb
<tr>
	<td class='first'><%= severity.sig_id %></td>
	<td><%= severity.name %></td>
	<td><%= severity.bg_color %></td>
	<td><%= severity.text_color %></td>
	<td><%= number_with_delimiter severity.signatures.count %></td>
	<td><%= number_with_delimiter severity.events_count %></td>
	<td><span class='severity-example' style='background-color:<%= severity.bg_color %>;color:<%= severity.text_color %>'><%= severity.sig_id %></span></td>
	<td><%= link_to "Edit", edit_severity_path(severity) %></td>
	
	<% if severity.locked? %>
		<td class='last'><%= image_tag('icons/lock.png') %></td>
	<% else %>
		<td class='last'><%= link_to image_tag("icons/destroy.png", :size => '16x16', :class => 'trash'), severity_path(severity), :method => :delete, :confirm => 'Are you sure you want to remove this severity?' %></td>
	<% end %>
	
</tr>

app/views/severities/edit.html.erb
<%= title "Edit Severity" do -%>

	<%= render :partial => 'settings/menu' %>
	
<%- end -%>


<%= render 'form' %>

app/views/severities/index.html.erb
<%= title "Severity Settings" do -%>

	<%= menu_item "Add Severity", new_severity_path, 'icons/add.png' %>
	<%= render :partial => 'settings/menu' %>
	
<%- end -%>

<%= render :partial => 'severities/severities' %>

app/views/severities/index.js.erb
$('div#severities').replaceWith("<%= escape_javascript(render(:partial => 'severities/severities', :locals => { :severities => @severities })) %>");
$('div.content, tbody.content').fadeTo(500, 1);
Snorby.helpers.remove_click_events(false);
$.scrollTo('#header', 500);
flash();

app/views/severities/new.html.erb
<%= title "New Severity" do -%>

	<%= render :partial => 'settings/menu' %>
	
<%- end -%>

<%= render 'form' %>

app/views/severities/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_severity_path(@severity) %> |
<%= link_to 'Back', severities_path %>